services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my-db
      MYSQL_USER: tester
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
