services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://owt-mysql-db:3306/my-db
      SPRING_DATASOURCE_USERNAME: tester
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.3.0
    container_name: owt-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my-db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: tester
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/kafka/data

volumes:
  db-data:
  kafka-data:
