services:
  db:
    image: mysql:8.3.0
    container_name: owt-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my-db
      MYSQL_USER: tester
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql

  db_test:
    image: mysql:8.3.0
    container_name: owt-mysql-db-test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: test-db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test1234
    volumes:
      - db-test-data:/var/lib/mysql

volumes:
  db-data:
  db-test-data: